version: '3'
services:
    nginx:
        image: nginx
        ports:
        - 80:80
        - 80:80
        volumes:
        - ./html:/app/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

    # drupal:
    #     build: apachedrupal
    #     ports:
    #         - 8000:80
    #         - 8443:443
    #     volumes:
    #         - ./drupal:/app/drupal
    #         - ./apachedrupal/drupal.conf:/etc/apache2/sites-enabled/drupal.conf

    #         - ./apache/wildcert.pem:/etc/ssl/certs/wildcert.pem
    #         - ./apache/wildkey.key:/etc/ssl/private/wildkey.key

    # web:
    #     build: apache
    #     ports:
    #         - 80:80
    #         - 443:443
    #     volumes:
    #         - ./wordpress:/app/wordpress
    #         - ./apache/wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf

    #         - ./prestashop:/app/prestashop
    #         - ./apache/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf

    #         - ./apache/wildcert.pem:/etc/ssl/certs/wildcert.pem
    #         - ./apache/wildkey.key:/etc/ssl/private/wildkey.key

    db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=abc123..
            - MYSQL_DATABASE=tarefa
            - MYSQL_USER=a22yagormTarefa
            - MYSQL_PASSWORD=a22yagormTarefaPW
        volumes:
            - baseDatos:/var/lib/mysql
            - ./db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql

volumes:
    baseDatos: